### ISSUE TITLE
Switch to Mapzen.js

### ISSUE THREAD

**Issue by migurski** [mapzen/data-pages#164]
Upgrade Tangram by way of switching to Mapzen.js for the left-pane map.

**Comment by bcamper** [comment]
👍

**Comment by binx** [comment]
```if (this.hasWebGL() === true) {
        var layer = Tangram.leafletLayer({
          attribution: '<a href="https://mapzen.com/tangram">Tangram</a> | <a href="http://www.openstreetmap.org/copyright">&copy; OSM contributors</a> | <a href="https://mapzen.com/">Mapzen</a>'
        });
      } else {
        var layer = L.tileLayer('https://stamen-tiles.a.ssl.fastly.net/toner-lite/{z}/{x}/{y}.png', {
          attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.',
        });
      }```

@hanbyul-here how should I run this test using mapzen.js?

**Comment by hanbyul-here** [comment]
`mapzen.js` doesn't offer fallback tile options, but  you can overwrite tile layer. 

```
var map = L.Mapzen.map(...);
if(!this.hasWebGL()) {
L.tileLayer('https://stamen-tiles.a.ssl.fastly.net/toner-lite/{z}/{x}/{y}.png', {}).addTo(map);
}
```
(This will display OSM basic tile first, then show stamen tiles though) 

This doesn't work now because mapzen.js is waiting fot Tangram to be loaded, then detect there is webgl or not, then fallback. (which means it is highly possible to be triggered later than overwriting layer) I can make detecting process goes first then waiting for webgl. I will push the fix, will report here.

**Comment by hanbyul-here** [comment]
actually we can make default fallback tile as Stamen's toner when `refill` is set as option. 💭 I wonder it is good idea or not.

**Comment by binx** [comment]
@hanbyul-here that fallback sounds good to me... or at least documentation on the README about how to add a fallback.
Also, is it possible to remove the console logs about `given scene` and `using scene`?

**Comment by hanbyul-here** [comment]
- Mapzen.js 0.1.3 now has an option for `fallbackTile` :) check out https://github.com/mapzen/mapzen.js#map

**Comment by binx** [comment]
thanks @hanbyul-here! :D
